# Final Modeling

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, cross_validate, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score, make_scorer
from sklearn.pipeline import make_pipeline

In [2]:
df = pd.read_csv('oecd_data_cleaned.csv')

In [3]:
df.head()

,country,region,health_exp_pct_gdp,continent,iso3,year,gdp_per_capita,gdp,gdp_volume_market_prices,cpi,...,other_nonproperty_tax_pct_gdp,property_income_pct_gdp,total_expenditure,total_revenue,total_expense_pct_gdp,total_revenue_pct_gdp,public_finance_trait,developing,life_expectancy_outcome_3,life_expectancy_outcome_5
0,Australia,Oceania,6.467,Oceania,AUS,1990.0,17838.1,4.136590e+11,8.625100e+11,0.494619,...,NaN,1.83,NaN,NaN,NaN,NaN,NaN,0.0,77.9,77.8
1,Australia,Oceania,6.762,Oceania,AUS,1991.0,18177.5,4.166640e+11,8.510460e+11,0.510977,...,NaN,2.08,NaN,NaN,NaN,NaN,NaN,0.0,77.9,78.1
2,Australia,Oceania,6.828,Oceania,AUS,1992.0,19157.7,4.323100e+11,8.767390e+11,0.515928,...,NaN,2.28,NaN,NaN,NaN,NaN,NaN,0.0,77.8,78.4
3,Australia,Oceania,6.844,Oceania,AUS,1993.0,20184.9,4.552010e+11,9.126430e+11,0.524968,...,NaN,2.74,NaN,NaN,NaN,NaN,NaN,0.0,78.1,78.6
4,Australia,Oceania,6.872,Oceania,AUS,1994.0,21432.8,4.826680e+11,9.559860e+11,0.535084,...,0.66,1.98,NaN,2.124420e+11,NaN,44.01,NaN,0.0,78.4,78.9